#pragma once
#include <iostream>
#include <vector>
#include <boost/asio.hpp>
#include <boost/bind.hpp>
#include <functional>
#include <Windows.h>
#include <algorithm>
#include <string>
#include <exception>
